<a href="https://colab.research.google.com/github/hjohn218/AVR/blob/main/Understanding%20Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#Work exercise on vectors
#importing the library that I need to use calculations
import numpy as np
#defining np.
myShort = np.short(15)
#arrays defined
a = np.array([1,2,3,4])
b = np.array([2,2,4,4])
#Checks whether the individual elements in a equal to b
#a[0] not equal to b[0] so it is false
#a[1] it equals to b[1] so it is true
#The output is a vector of a type of bool
#printing solutions
print(a == b)
print(a < b)

#Logical Operations
#Boolean operators AND, OR, XOR, NOT
c = np.array([True, False, True, False])
d = np.array([True, True, False, False])
#prints solutions
print(np.logical_or(c,d))
print(np.logical_and(c,d))
# The original line 'print(np.logical_not(c,d))' has an issue: logical_not only takes one array.
# If the intent was to apply NOT to 'c', it should be 'print(np.logical_not(c))'
# If the intent was to apply NOT to 'd', it should be 'print(np.logical_not(d))'
# For now, I'll assume the user meant to apply logical_not to 'c' as an example.
print(np.logical_not(c)) # Fixed to use only one argument for logical_not
print(np.logical_xor(c,d))
#Matrix
e = np.array([[1,2,3], [4,5,6]])
f = np.array([[1,2,3], [3,4,5], [5,6,7]])
print(a.dot(b))
#advanced matrix operations
changeIt = np.array([1,2,3,4,5,6,7,8])
print(changeIt)
changeIt = changeIt.reshape(2,4)
print(changeIt)
changeIt = changeIt.reshape(2,2,2)
print(changeIt)
changeIT = np.array([1,2,3,4,5,6,7,8])
print(changeIT)
changeIT = np.transpose(changeIT)
print(changeIT)
print(np.identity(4))
#g = np.array([[1,2,3], [4,5,6]])
#h = np.linalg.inv(g)
#print(np.aliclose(np.dot(g,h), np.identity(2)))

#on page 68

[False  True False  True]
[ True False  True False]
[ True  True  True False]
[ True False False False]
[False  True False  True]
[False  True  True False]
34
[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


LinAlgError: Last 2 dimensions of the array must be square